-- Demo data now lives in migration `0003_seed_demo_data.sql`, so it is applied to
-- BOTH local (`db reset`) and Cloud (`db push`) — no longer local-only.
--
-- This seed file is intentionally empty to avoid duplicate-key errors on `db reset`
-- (migrations run before the seed step, so 0003 has already inserted the demo users,
-- projects, stages, and assignment). Add any strictly local-only, throwaway data here.
